# Generated by Django 5.1.3 on 2025-02-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_dietrecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietRecommendation',
        ),
    ]
