# Generated by Django 5.1.3 on 2025-02-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_delete_dietrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='bmi_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
