# Generated by Django 5.1.3 on 2025-02-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_recommendation_bmi_recommendation_bmi_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='bmi_category',
        ),
    ]
