# Generated by Django 5.1.3 on 2025-02-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_recommendation_bmi_recommendation_bmi_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='bmi_category',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='meal_calories',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended_calories',
        ),
    ]
