# Generated by Django 5.1.3 on 2025-02-14 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_remove_recommendation_bmi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi_category', models.CharField(max_length=20)),
                ('recommended_calories', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], max_length=10)),
                ('recipe_name', models.CharField(max_length=200)),
                ('calories', models.IntegerField()),
                ('ingredients', models.JSONField()),
                ('instructions', models.JSONField()),
                ('diet_recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='recommendation.dietrecommendation')),
            ],
        ),
    ]
