# Generated by Django 5.1.3 on 2025-02-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0008_dietrecommendation_mealrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrecommendation',
            name='diet_recommendation',
        ),
        migrations.DeleteModel(
            name='DietRecommendation',
        ),
        migrations.DeleteModel(
            name='MealRecommendation',
        ),
    ]
