# Generated by Django 5.1.3 on 2025-02-14 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0009_remove_mealrecommendation_diet_recommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
                ('ingredients', models.JSONField()),
                ('instructions', models.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='diet_recommendation_result',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='bmi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='bmi_category',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='activity',
            field=models.CharField(choices=[('no_exercise', 'No Exercise'), ('light_exercise', 'Light Exercise'), ('moderate_exercise', 'Moderate Exercise'), ('very_active', 'Very Active'), ('extra_active', 'Extra Active')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='weight_loss_plan',
            field=models.CharField(choices=[('maintain_weight', 'Maintain Weight'), ('mild_weight_loss', 'Mild Weight Loss'), ('weight_loss', 'Weight Loss'), ('extreme_weight_loss', 'Extreme Weight Loss')], max_length=20),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='breakfast_recipes',
            field=models.ManyToManyField(related_name='breakfast_recommendations', to='recommendation.recipe'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='dinner_recipes',
            field=models.ManyToManyField(related_name='dinner_recommendations', to='recommendation.recipe'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='lunch_recipes',
            field=models.ManyToManyField(related_name='lunch_recommendations', to='recommendation.recipe'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='snacks_recipes',
            field=models.ManyToManyField(related_name='snacks_recommendations', to='recommendation.recipe'),
        ),
    ]
