# Generated by Django 5.1.3 on 2025-02-14 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0010_recipe_alter_recommendation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='breakfast_recipes',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='dinner_recipes',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='lunch_recipes',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='snacks_recipes',
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], max_length=20)),
                ('calories_allocated', models.IntegerField()),
                ('recipes', models.ManyToManyField(related_name='meal_plans', to='recommendation.recipe')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='recommendation.recommendation')),
            ],
        ),
    ]
