# Generated by Django 5.1.3 on 2025-03-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0011_remove_recommendation_breakfast_recipes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
