# Generated by Django 5.1.3 on 2025-03-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0012_recipe_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='SaturatedFat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbohydrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cholesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
